version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8080:80"